### PR TITLE
Use brave-browser release url; download linux symbols

### PR DESCRIPTION
**Pull request by mbacchi**

### CODE REVIEW

**Comment by bkero** [comment]
Can we do a clean cutover for this, or are we going to need to process logs of crashes from brave-browser-builds?

**Comment by mbacchi** [comment]
I'm not positive but if I were to guess the first unofficial release is the first build we'll really want to process crash dumps for, at least en masse. If it makes more sense I could run the current script manually to fetch all the current releases on the two crash worker hosts. After that I would update the fetch script and setup the nightly cron job. Does that seem like a more comprehensive plan?

Or do you think I should allow for both in the script for future iterations of crash workers to have the ability to get those older releases?

**Comment by aekeus** [comment]
A clean cut over is fine. We are in the testing phase right now and crashes for previous versions are of limited value. We will want to have the option to parse N previous versions of brave-core for each of the channels. cc @bbondy

**Review by bkero — APPROVED** [review]
Since we can do a clean cutover this is fine.

**Pull request merged**
